version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn install
  pre_build:
    commands:
      - yarn test:cov
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - yarn publish

