version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "installing stuff"
      - yarn install
  pre_build:
    commands:
      - echo "pre-build commands"
  build:
    commands:
      - echo "build commands"
      - yarn build
  post_build:
    commands:
      - echo "post-build commands"